### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by auspex** [panubo/docker-monit#1]
This is interesting, but why on earth does your usage example show it running with `--privileged` and mounting `/dev`?  (Oh, I didn't even notice you were mounting `/`, that's a _serious_ security issue)

Mounting /dev _may_ not be a security issue in itself, but mounting it in a privileged container certainly is. Having recently found somebody running a bitcoin miner in my docker host, I'm a little touchy about security :-)

**Comment by macropin** [comment]
Depends on your usage. We've used this to monitor the docker host. Having access to these devices is necessary. Alternatively install Monit directly on the the host and go nuts!

**Comment by auspex** [comment]
It really doesn't depend on your usage. Giving a container root access to /
is extremely insecure.  There's nothing wrong with the container
configuration itself, only the suggested usage.

derek

**Comment by macropin** [comment]
I'm not denying that there are security implications. However this is no less secure than running monit directly on the host.
